### PR TITLE
Duplicate symbols fix and test

### PR DESCRIPTION
**Pull request by rolandpersson**
I discovered some link errors due to duplicate symbols when I upgraded to 0.1.0. This happens for me because I'm using the tiny cnn headers in more than one translation unit. 

This pull request contains some inline keywords to fix the link errors and an added .cpp file included in the tiny_cnn_test in order to try and catch this type of error when they are introduced.

### CODE REVIEW

**Comment by nyanp** [comment]
@rolandpersson 
Oh it's a critical bug. Adding the test is very good idea, thank you veru much :)
